feat(emoji_gen): abort if dependencies aren't found
abort the script if bundler or jq aren't found installed on the system.

diff --git a/scripts/emoji_gen b/scripts/emoji_gen
--- a/scripts/emoji_gen
+++ b/scripts/emoji_gen
@@ -1,5 +1,10 @@
 #!/bin/sh
-# NOTE: make sure you have ruby, bundler, and jq installed
+
+if [ ! "$(command -v bundler)" ] || [ ! "$(command -v jq)" ]; then
+  echo "ruby or jq is not installed, aborting" >&2 
+  exit
+fi
+
 
 tmp_dir="/tmp/emoji-data"
 emoji_file="$HOME/.local/share/emojis.json"
